---
- hosts: all
  become: yes
  vars:
    - myname: template example
  tasks:
  - name: creating a file with static content
    copy:
      src: hello.txt
      dest: /home/hello
  - name: create a file with dynamic content
    template:
      src: message.j2
      dest: /home/message

