---
 - hosts: all
   become: yes
   tasks:
     - name: install apache and update
       apt:
         update_cache: yes
         name: apache2
         state: present
     - name: restart the apache service
       service:
         name: apache2
         state: restarted
         enabled: yes
     - name: Installing the php modulues
       apt:
          name:
          state: present
       with_items:
       - php 
       - libapache2-mod-php 
       - php-mysql
     - name: restart the apache after installations
       service:
         name: apache2
         state: restarted
         enabled: yes
        