---
- hosts: all
  become: yes
  tasks:
   - name: update ubuntu
     apt:
       update_cache: yes
       state: present
     when: ansible_os_family == "Debian"
   - name: upgrade all packages
     yum:
        name: "*" 
        state: latest
     when: ansible_os_family == "RedHat"
   - name: tomcat install
     package:
       name: "{{ pack_name }}"
       state: present
       enabled: yes
  handlers:
    - name: restart tomcat 
      service:
        name: "{{ pack_name }}"
        state: restarted

