---
- hosts: all
  become: yes
  tasks:
  - name: install apache server
    package:
      name: "{{ pack_name }}"
      state: present
    notify:
    - restart apache
  - name: install php packages
    package:
      name: "{{ pack_name }}"
      state: present
    with_items: "{{ php_modules }}"
    notify:
    - restart apache
  - name: download webpage
    get_url:
      url: https://raw.githubusercontent.com/sandeepmchary/prac/master/Lamp/info.php
      dest: /var/www/html/info.php
    notify:
      - restart apache

  handlers:
  - name: restart apache
    service:
      name: "{{ pack_name }}"
      state: restarted
